language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
  - oraclejdk8

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt g8Test

  ## Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -ma,e "ivydata-*.properties" | xargs rm